parameters:
    mon_parametre: ma_valeur


services:
#    ms_platform.example:
#        class: MS\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ms_platform.antispam:
        class: MS\PlatformBundle\Antispam\MSAntispam
        arguments: [@mailer, %locale%, 50] # Tableau d'arguments

